### PR TITLE
Bump Polaris and App Bridge versions

### PR DESCRIPTION
**Pull request by hannachen**
### WHY are these changes introduced?

I am assisting with a [react summit workshop](https://remote.reactsummit.com/workshops-3h) that will teach attendees how to create an app using the Shopify CLI. We'll be referring to/showing the Polaris and App Bridge docs on shopify.dev, and we would like the node app template to reflect the docs as closely as possible.

### WHAT is this pull request doing?

Update the version of Polaris and App Bridge in the scaffolded app to the latest.

### CODE REVIEW

**Comment by andyw8** [comment]
@hannachen did you mean to remove `package-lock.json`?

**Comment by andyw8** [comment]
Oh, it's not fully removed, but it is much small for some reason:

`68 additions, 20,986 deletions`

**Comment by hannachen** [comment]
> Oh, it's not fully removed, but it is much smaller for some reason:
> 
> `68 additions, 20,986 deletions`

Oh wow, I'm not sure what happened there. I simply included any changes resulted from `npm install`. I did end up using the same version of `app-bridge-react` and `app-bridge-utils`, not sure if something like that would remove lines from the lock file?

**Comment by andyw8** [comment]
Looking at the diff locally (it's too big for GitHub), it seems you might have been using an older version of `npm`?

```diff
 {
   "name": "shopify-app-node",
   "version": "1.0.0",
-  "lockfileVersion": 2,
+  "lockfileVersion": 1,
   "requires": true,
```

**Comment by hannachen** [comment]
> Looking at the diff locally (it's too big for GitHub), it seems you might have been using an older version of `npm`?
> 
> ```diff
>  {
>    "name": "shopify-app-node",
>    "version": "1.0.0",
> -  "lockfileVersion": 2,
> +  "lockfileVersion": 1,
>    "requires": true,
> ```

Very possible! Do you know what version of npm I should be using to generate this? I'll run it again with the correct version.

**Comment by paulomarg** [comment]
Hi! I believe you'll have to use npm v7+: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion

**Comment by andyw8** [comment]
That looks better, did you :tophat: ?

**Review by paulomarg — APPROVED** [review]
🎩 ed, was able to run, install and uninstall the app. Since our usage of Polaris in the base app is very limited at checkout time, I don't expect we'll have issues there!

**Pull request merged**
