### PR TITLE
simplify app-bridge initialization code

### PR DESCRIPTION
**Pull request by joeyfreund**
### WHY are these changes introduced?

Simplify starter code (originally attempted in #743 )

### WHAT is this pull request doing?

Removing a redundant line of code.

### CODE REVIEW

**Comment by joeyfreund** [comment]
@paulomarg , I saw [your comment here](https://github.com/Shopify/shopify-app-node/pull/743#issuecomment-1083247401).

From what I'm seeing, our docs are a tiny bit misleading - The `forceRedirect` option is [`true` by default in production environment, but it is `false` by default in development environment](https://github.com/Shopify/app-bridge/blob/main/packages/app-bridge/src/client/Client.ts#L33).

It was a nice attempt to try and simplify it, but I feel like it's better to forget about it for now.
Thanks for 🎩 ing and letting me know about the redirect issue 🙏 

cc @vividviolet , @henrytao-me

**Comment by paulomarg** [comment]
Agreed that we should keep it as is for consistency across the environments in the generated app!

**Comment by vividviolet** [comment]
Maybe as a compromise we should add a comment above the `forceRedirect: true` to say that this can be turned off if you want to allow opening your app without Admin for testing? I just realized we have no docs on this config property. We only have docs for the React config: https://shopify.dev/apps/tools/app-bridge/react-components/provider#appconfig

I've seen lots of questions from developers about this. Sometimes they just want to see their app UI and test it without needing to open it in Admin.

**Comment by paulomarg** [comment]
> I've seen lots of questions from developers about this. Sometimes they just want to see their app UI and test it without needing to open it in Admin.

Do you think this will continue to be a problem, now that we have HMR working out of the box for the UI?

That being said, I agree that the comment is probably helpful in either case!

**Comment by joeyfreund** [comment]
> we should update our docs and add type annotations

💯 
It came up (specifically, around the config object) in the chat that Elana and I had about docs - Our shopify.dev content isn't consistent (some features have API docs, some only have code examples). We will fix it.

**Pull request closed without merging**
